"""
My first application
"""
import toga
from PIL import Image
from toga.style import Pack
from toga.style.pack import COLUMN, ROW
from functools import partial
from random import shuffle
from toga.constants import MAGENTA, BLUE, PURPLE, GRAY, ORANGE, YELLOW, GREEN, CYAN, GOLD, RED, LIME

class Perodictable(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))
        box1 = toga.Box()
        box2 = toga.Box()
        box3 = toga.Box()
        box4 = toga.Box()
        box5 = toga.Box()
        box6 = toga.Box()
        box7 = toga.Box()
        box8 = toga.Box()
        box9 = toga.Box()
        box10 = toga.Box(style = Pack(padding_left = 300))
        self.box10 = toga.Box()
        self.button = toga.Button("H", on_press=partial(self.my_callback, element = 0, element_picture = 'H.png'),style= Pack(height=40,width=40,background_color= BLUE))
        self.button1 = toga.Button('He', on_press=partial(self.my_callback,element = 1, element_picture = 'He.png'), style = Pack(height=40,width=40,padding_left = 660, background_color= GOLD))
        self.button2 = toga.Button('Li', on_press=partial(self.my_callback,element = 2, element_picture = 'Li.png'), style=Pack(height=40, width = 40,background_color= MAGENTA))
        self.button3 = toga.Button('Be', on_press=partial(self.my_callback,element = 3, element_picture = 'Be.png'), style=Pack(height=40, width = 40, background_color= PURPLE))
        self.button4 = toga.Button('B', on_press=partial(self.my_callback,element = 4, element_picture = 'B.png'), style=Pack(height=40, width = 40, padding_left = 420, background_color= GREEN))
        self.button5 = toga.Button('C', on_press=partial(self.my_callback,element = 5, element_picture = 'C.png'), style=Pack(height=40, width = 40, background_color= BLUE))
        self.button6 = toga.Button('N', on_press=partial(self.my_callback,element = 6, element_picture = 'O.png'), style=Pack(height=40, width = 40, background_color= BLUE))
        self.button7 = toga.Button('O', on_press=partial(self.my_callback,element = 7, element_picture = 'F.png'), style=Pack(height=40, width = 40, background_color= BLUE))
        self.button8 = toga.Button('F', on_press=partial(self.my_callback,element = 8, element_picture = 'F.png'), style=Pack(height=40, width = 40, background_color= YELLOW))
        self.button9 = toga.Button('Ne', on_press=partial(self.my_callback,element = 9, element_picture = 'Ne.png'), style=Pack(height=40, width = 40, background_color= GOLD))
        self.button10 = toga.Button('Na', on_press=partial(self.my_callback,element = 10, element_picture = 'Na.png'), style=Pack(height=40, width = 40, background_color= MAGENTA))
        self.button11 = toga.Button('Mg', on_press=partial(self.my_callback,element = 11, element_picture = 'Mg.png'), style=Pack(height=40, width = 40, background_color= PURPLE))
        self.button12 = toga.Button('Al', on_press=partial(self.my_callback,element = 12, element_picture = 'Al.png'), style=Pack(height=40, width = 40, padding_left = 420, background_color= ORANGE))
        self.button13 = toga.Button('Si', on_press=partial(self.my_callback,element = 13, element_picture = 'Si.png'), style=Pack(height=40, width = 40, background_color= GREEN))
        self.button14 = toga.Button('P', on_press=partial(self.my_callback,element = 14, element_picture = 'P.png'), style=Pack(height=40, width = 40, background_color= BLUE))
        self.button15 = toga.Button('S', on_press=partial(self.my_callback,element = 15, element_picture = 'S.png'), style=Pack(height=40, width = 40, background_color= BLUE))
        self.button16 = toga.Button('Cl', on_press=partial(self.my_callback,element = 16, element_picture = 'Cl.png'), style=Pack(height=40, width = 40, background_color= YELLOW))
        self.button17 = toga.Button('Ar', on_press=partial(self.my_callback,element = 17, element_picture = 'Ar.png'), style=Pack(height=40, width = 40, background_color= GOLD))
        self.button18 = toga.Button("K", on_press=partial(self.my_callback, element = 18, element_picture = 'K.png'),style= Pack(height=40,width=40, background_color= MAGENTA))
        self.button19 = toga.Button("Ca", on_press=partial(self.my_callback, element = 19, element_picture = 'Ca.png'),style= Pack(height=40,width=40, background_color= PURPLE))
        self.button20 = toga.Button("Sc", on_press=partial(self.my_callback, element = 20, element_picture = 'Sc.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button21 = toga.Button("Ti", on_press=partial(self.my_callback, element = 21, element_picture = 'Ti.png'),style= Pack(height=40,width=40, padding_left=20, background_color= CYAN))
        self.button22 = toga.Button("V", on_press=partial(self.my_callback, element = 22, element_picture = 'V.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button23 = toga.Button("Cr", on_press=partial(self.my_callback, element = 23, element_picture = 'Cr.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button24 = toga.Button("Mn", on_press=partial(self.my_callback, element = 24, element_picture = 'Mn.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button25 = toga.Button("Fe", on_press=partial(self.my_callback, element = 25, element_picture = 'Fe.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button26 = toga.Button("Co", on_press=partial(self.my_callback, element = 26, element_picture = 'Co.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button27 = toga.Button("Ni", on_press=partial(self.my_callback, element = 27, element_picture = 'Ni.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button28 = toga.Button("Cu", on_press=partial(self.my_callback, element = 28, element_picture = 'Cu.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button29 = toga.Button("Zn", on_press=partial(self.my_callback, element = 29, element_picture = 'Zn.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button30 = toga.Button("Ga", on_press=partial(self.my_callback, element = 30, element_picture = 'Ga.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button31 = toga.Button("Ge", on_press=partial(self.my_callback, element = 31, element_picture = 'Ge.png'),style= Pack(height=40,width=40, background_color= GREEN))
        self.button32 = toga.Button("As", on_press=partial(self.my_callback, element = 32, element_picture = 'As.png'),style= Pack(height=40,width=40, background_color= GREEN))
        self.button33 = toga.Button("Se", on_press=partial(self.my_callback, element = 33, element_picture = 'Se.png'),style= Pack(height=40,width=40, background_color= BLUE))
        self.button34 = toga.Button("Br", on_press=partial(self.my_callback, element = 34, element_picture = 'Br.png'),style= Pack(height=40,width=40, background_color= YELLOW))
        self.button35 = toga.Button("Kr", on_press=partial(self.my_callback, element = 35, element_picture = 'Kr.png'),style= Pack(height=40,width=40, background_color= GOLD))
        self.button36 = toga.Button("Rb", on_press=partial(self.my_callback, element = 36, element_picture = 'Rb.png'),style= Pack(height=40,width=40, background_color= MAGENTA))
        self.button37 = toga.Button("Sr", on_press=partial(self.my_callback, element = 37, element_picture = 'Sr.png'),style= Pack(height=40,width=40, background_color= PURPLE))
        self.button38 = toga.Button("Y", on_press=partial(self.my_callback, element = 38, element_picture = 'Y.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button39 = toga.Button("Zr", on_press=partial(self.my_callback, element = 39, element_picture = 'Zr.png'),style= Pack(height=40,width=40, padding_left=20, background_color= CYAN))
        self.button40 = toga.Button("Nb", on_press=partial(self.my_callback, element = 40, element_picture = 'Nb.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button41 = toga.Button("Mo", on_press=partial(self.my_callback, element = 41, element_picture = 'Mo.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button42 = toga.Button("Tc", on_press=partial(self.my_callback, element = 42, element_picture = 'Tc.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button43 = toga.Button("Ru", on_press=partial(self.my_callback, element = 43, element_picture = 'Ru.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button44 = toga.Button("Rh", on_press=partial(self.my_callback, element = 44, element_picture = 'Rh.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button45 = toga.Button("Pd", on_press=partial(self.my_callback, element = 45, element_picture = 'Pd.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button46 = toga.Button("Ag", on_press=partial(self.my_callback, element = 46, element_picture = 'Ag.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button47 = toga.Button("Cd", on_press=partial(self.my_callback, element = 47, element_picture = 'Cd.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button48 = toga.Button("In", on_press=partial(self.my_callback, element = 48, element_picture = 'In.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button49 = toga.Button("Sn", on_press=partial(self.my_callback, element = 49, element_picture = 'Sn.png'),style= Pack(height=40,width=40, background_color=ORANGE))
        self.button50 = toga.Button("Sb", on_press=partial(self.my_callback, element = 50, element_picture = 'Sb.png'),style= Pack(height=40,width=40, background_color=GREEN))
        self.button51 = toga.Button("Te", on_press=partial(self.my_callback, element = 51, element_picture = 'Te.png'),style= Pack(height=40,width=40, background_color=GREEN))
        self.button52 = toga.Button("I", on_press=partial(self.my_callback, element = 52, element_picture = 'I.png'),style= Pack(height=40,width=40, background_color=YELLOW))
        self.button53 = toga.Button("Xe", on_press=partial(self.my_callback, element = 53, element_picture = 'Xe.png'),style= Pack(height=40,width=40, background_color= GOLD))
        self.button54 = toga.Button("Cs", on_press=partial(self.my_callback, element = 54, element_picture = 'Cs.png'),style= Pack(height=40,width=40, background_color= MAGENTA))
        self.button55 = toga.Button("Ba", on_press=partial(self.my_callback, element = 55, element_picture = 'Ba.png'),style= Pack(height=40,width=40, background_color= PURPLE))
        self.button56 = toga.Button("La", on_press=partial(self.my_callback, element = 56, element_picture = 'La.png'),style= Pack(height=40,width=40, background_color= LIME))
        self.button57 = toga.Button("Hf", on_press=partial(self.my_callback, element = 71, element_picture = 'Hf.png'),style= Pack(height=40,width=40, padding_left=20, background_color= CYAN))
        self.button58 = toga.Button("Ta", on_press=partial(self.my_callback, element = 72, element_picture = 'Ta.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button59 = toga.Button("W", on_press=partial(self.my_callback, element = 73, element_picture = 'W.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button60 = toga.Button("Re", on_press=partial(self.my_callback, element = 74, element_picture = 'Re.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button61 = toga.Button("Os", on_press=partial(self.my_callback, element = 75, element_picture = 'Os.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button62 = toga.Button("Ir", on_press=partial(self.my_callback, element = 76, element_picture = 'Ir.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button63 = toga.Button("Pt", on_press=partial(self.my_callback, element = 77, element_picture = 'Pt.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button64 = toga.Button("Au", on_press=partial(self.my_callback, element = 78, element_picture = 'Au.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button65 = toga.Button("Hg", on_press=partial(self.my_callback, element = 79, element_picture = 'Hg.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button66 = toga.Button("Ti", on_press=partial(self.my_callback, element = 80, element_picture = 'Ti.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button67 = toga.Button("Pb", on_press=partial(self.my_callback, element = 81, element_picture = 'Pb.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button68 = toga.Button("Bi", on_press=partial(self.my_callback, element = 82, element_picture = 'Bi.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button69 = toga.Button("Po", on_press=partial(self.my_callback, element = 83, element_picture = 'Po.png'),style= Pack(height=40,width=40, background_color= GREEN))
        self.button70 = toga.Button("At", on_press=partial(self.my_callback, element = 84, element_picture = 'At.png'),style= Pack(height=40,width=40, background_color= YELLOW))
        self.button71 = toga.Button("Rn", on_press=partial(self.my_callback, element = 85, element_picture = 'Rn.png'),style= Pack(height=40,width=40, background_color= GOLD))
        self.button72 = toga.Button("Fr", on_press=partial(self.my_callback, element = 86, element_picture = 'Fr.png'),style= Pack(height=40,width=40, background_color= MAGENTA))
        self.button73 = toga.Button("Ra", on_press=partial(self.my_callback, element = 87, element_picture = 'Ra.png'),style= Pack(height=40,width=40, background_color= PURPLE))
        self.button74 = toga.Button("Ac", on_press=partial(self.my_callback, element = 88, element_picture = 'Ac.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button75 = toga.Button("Rf", on_press=partial(self.my_callback, element = 103, element_picture = 'Rf.png'),style= Pack(height=40,width=40, padding_left=20, background_color= CYAN))
        self.button76 = toga.Button("Db", on_press=partial(self.my_callback, element = 104, element_picture = 'Db.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button77 = toga.Button("Sg", on_press=partial(self.my_callback, element = 105, element_picture = 'Sg.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button78 = toga.Button("Bh", on_press=partial(self.my_callback, element = 106, element_picture = 'Bh.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button79 = toga.Button("Hs", on_press=partial(self.my_callback, element = 107, element_picture = 'Hs.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button80 = toga.Button("Mt", on_press=partial(self.my_callback, element = 108, element_picture = 'Mt.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button81 = toga.Button("Ds", on_press=partial(self.my_callback, element = 109, element_picture = 'Ds.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button82 = toga.Button("Rg", on_press=partial(self.my_callback, element = 110, element_picture = 'Rg.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button83 = toga.Button("Cn", on_press=partial(self.my_callback, element = 111, element_picture = 'Cn.png'),style= Pack(height=40,width=40, background_color= CYAN))
        self.button84 = toga.Button("Nh", on_press=partial(self.my_callback, element = 112, element_picture = 'Nh.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button85 = toga.Button("Fl", on_press=partial(self.my_callback, element = 113, element_picture = 'Fl.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button86 = toga.Button("Mc", on_press=partial(self.my_callback, element = 114, element_picture = 'Mc.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button87 = toga.Button("Lv", on_press=partial(self.my_callback, element = 115, element_picture = 'Lv.png'),style= Pack(height=40,width=40, background_color= ORANGE))
        self.button88 = toga.Button("Ts", on_press=partial(self.my_callback, element = 116, element_picture = 'Ts.png'),style= Pack(height=40,width=40, background_color= YELLOW))
        self.button89 = toga.Button("Og", on_press=partial(self.my_callback, element = 117, element_picture = 'Og.png'),style= Pack(height=40,width=40, background_color= GOLD))
        self.button90 = toga.Button("Ce", on_press=partial(self.my_callback, element = 57, element_picture = 'Ce.png'),style= Pack(height=40,width=40, padding_left = 140, padding_top = 20, background_color= LIME))
        self.button91 = toga.Button("Pr", on_press=partial(self.my_callback, element = 58, element_picture = 'Pr.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button92 = toga.Button("Nd", on_press=partial(self.my_callback, element = 59, element_picture = 'Nd.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button93 = toga.Button("Pm", on_press=partial(self.my_callback, element = 60, element_picture = 'Pm.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button94 = toga.Button("Sm", on_press=partial(self.my_callback, element = 61, element_picture = 'Sm.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button95 = toga.Button("Eu", on_press=partial(self.my_callback, element = 62, element_picture = 'Eu.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button96 = toga.Button("Gd", on_press=partial(self.my_callback, element = 63, element_picture = 'Gd.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button97 = toga.Button("Tb", on_press=partial(self.my_callback, element = 64, element_picture = 'Tb.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button98 = toga.Button("Dy", on_press=partial(self.my_callback, element = 65, element_picture = 'Dy.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button99 = toga.Button("Ho", on_press=partial(self.my_callback, element = 66, element_picture = 'Ho.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button100 = toga.Button("Er", on_press=partial(self.my_callback, element = 67, element_picture = 'Er.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button101 = toga.Button("Tm", on_press=partial(self.my_callback, element = 68, element_picture = 'Tm.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button102 = toga.Button("Yb", on_press=partial(self.my_callback, element = 69, element_picture = 'Yb.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button103 = toga.Button("Lu", on_press=partial(self.my_callback, element = 70, element_picture = 'Lu.png'),style= Pack(height=40,width=40, padding_top = 20, background_color= LIME))
        self.button104 = toga.Button("Th", on_press=partial(self.my_callback, element = 89, element_picture = 'Th.png'),style= Pack(height=40,width=40, padding_left = 140, background_color= RED))
        self.button105 = toga.Button("Pa", on_press=partial(self.my_callback, element = 90, element_picture = 'Pa.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button106 = toga.Button("U", on_press=partial(self.my_callback, element = 91, element_picture = 'U.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button107 = toga.Button("Np", on_press=partial(self.my_callback, element = 92, element_picture = 'Np.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button108 = toga.Button("Pu", on_press=partial(self.my_callback, element = 93, element_picture = 'Pu.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button109 = toga.Button("Am", on_press=partial(self.my_callback, element = 94, element_picture = 'Am.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button110 = toga.Button("Cm", on_press=partial(self.my_callback, element = 95, element_picture = 'Cm.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button111 = toga.Button("Bk", on_press=partial(self.my_callback, element = 96, element_picture = 'Bk.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button112 = toga.Button("Cf", on_press=partial(self.my_callback, element = 97, element_picture = 'Cf.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button113 = toga.Button("Es", on_press=partial(self.my_callback, element = 98, element_picture = 'Es.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button114 = toga.Button("Fm", on_press=partial(self.my_callback, element = 99, element_picture = 'Fm.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button115 = toga.Button("Md", on_press=partial(self.my_callback, element = 100, element_picture = 'Md.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button116 = toga.Button("No", on_press=partial(self.my_callback, element = 101, element_picture = 'No.png'),style= Pack(height=40,width=40, background_color= RED))
        self.button117 = toga.Button("Lr", on_press=partial(self.my_callback, element = 102, element_picture = 'Lr.png'),style= Pack(height=40,width=40, background_color= RED))
        self.label3 = toga.Label(' ', style = Pack(height = 140, padding_left = 140))

        
        box1.add(self.button)
        box1.add(self.button1)

        box2.add(self.button2)
        box2.add(self.button3)
        box2.add(self.button4)
        box2.add(self.button5)
        box2.add(self.button6)
        box2.add(self.button7)
        box2.add(self.button8)
        box2.add(self.button9)

        box3.add(self.button10)
        box3.add(self.button11)
        box3.add(self.button12)
        box3.add(self.button13)
        box3.add(self.button14)
        box3.add(self.button15)
        box3.add(self.button16)
        box3.add(self.button17)

        box4.add(self.button18)
        box4.add(self.button19)
        box4.add(self.button20)
        box4.add(self.button21)
        box4.add(self.button22)
        box4.add(self.button23)
        box4.add(self.button24)
        box4.add(self.button25)
        box4.add(self.button26)
        box4.add(self.button27)
        box4.add(self.button28)
        box4.add(self.button29)
        box4.add(self.button30)
        box4.add(self.button31)
        box4.add(self.button32)
        box4.add(self.button33)
        box4.add(self.button34)
        box4.add(self.button35)

        box5.add(self.button36)
        box5.add(self.button37)
        box5.add(self.button38)
        box5.add(self.button39)
        box5.add(self.button40)
        box5.add(self.button41)
        box5.add(self.button42)
        box5.add(self.button43)
        box5.add(self.button44)
        box5.add(self.button45)
        box5.add(self.button46)
        box5.add(self.button47)
        box5.add(self.button48)
        box5.add(self.button49)
        box5.add(self.button50)
        box5.add(self.button51)
        box5.add(self.button52)
        box5.add(self.button53)

        box6.add(self.button54)
        box6.add(self.button55)
        box6.add(self.button56)
        box6.add(self.button57)
        box6.add(self.button58)
        box6.add(self.button59)
        box6.add(self.button60)
        box6.add(self.button61)
        box6.add(self.button62)
        box6.add(self.button63)
        box6.add(self.button64)
        box6.add(self.button65)
        box6.add(self.button66)
        box6.add(self.button67)
        box6.add(self.button68)
        box6.add(self.button69)
        box6.add(self.button70)
        box6.add(self.button71)

        box7.add(self.button72)
        box7.add(self.button73)
        box7.add(self.button74)
        box7.add(self.button75)
        box7.add(self.button76)
        box7.add(self.button77)
        box7.add(self.button78)
        box7.add(self.button79)
        box7.add(self.button80)
        box7.add(self.button81)
        box7.add(self.button82)
        box7.add(self.button83)
        box7.add(self.button84)
        box7.add(self.button85)
        box7.add(self.button86)
        box7.add(self.button87)
        box7.add(self.button88)
        box7.add(self.button89)

        box8.add(self.button90)
        box8.add(self.button91)
        box8.add(self.button92)
        box8.add(self.button93)
        box8.add(self.button94)
        box8.add(self.button95)
        box8.add(self.button96)
        box8.add(self.button97)
        box8.add(self.button98)
        box8.add(self.button99)
        box8.add(self.button100)
        box8.add(self.button101)
        box8.add(self.button102)
        box8.add(self.button103)

        box9.add(self.button104)
        box9.add(self.button105)
        box9.add(self.button106)
        box9.add(self.button107)
        box9.add(self.button108)
        box9.add(self.button109)
        box9.add(self.button110)
        box9.add(self.button111)
        box9.add(self.button112)
        box9.add(self.button113)
        box9.add(self.button114)
        box9.add(self.button115)
        box9.add(self.button116)
        box9.add(self.button117)





        main_box.add(box1)
        main_box.add(box2)
        main_box.add(box3)
        main_box.add(box4) 
        main_box.add(box5)
        main_box.add(box6)
        main_box.add(box7)
        main_box.add(box8)
        main_box.add(box9)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
    a = ['Hydrogen', "Helium", "Lithium","Beryllium", "Boron", "Carbon","Nitrogen","Oxygen","Fluorine" ,"Neon", "Sodium", "Magnesium","Aluminum","Silicon","Phosphorus","Sulfur","Chlorine" ,"Argon","Potassium","Calcium","Scandium","Titanium","Vanadium","Chromium","Manganese","Iron","Cobalt","Nickel","Copper","Zinc","Gallium","Germanium","Arsenic","Selenium","Bromine","Krypton","Rubidium","Strontium","Yttrium","Zirconium","Niobium","Molybdenum","Technetium","Ruthenium","Rhodium","Palladium","Silver","Cadmium","Indium","Tin","Antimony","Tellurium","Iodine","Xenon","Cesium","Barium","Lanthanum","Cerium","Praseodymium","Neodymium","Promethium","Samarium","Europium","Gadolinium","Terbium","Dysprosium","Holmium","Erbium","Thulium","Ytterbium","Lutetium","Hafnium","Tantalum","Tungsten","Rhenium","Osmium","Iridium","Platinum","Gold","Mercury","Thallium","Lead","Bismuth","Polonium","Astatine","Radon","Francium","Radium","Actinium","Thorium","Protactinium","Uranium","Neptunium","Plutonium","Americium","Curium","Berkelium","Californium","Einsteinium","Fermium","Mendelevium","Nobelium","Lawrencium","Rutherfordium","Dubnium","Seaborgium","Bohrium","Hassium","Meitnerium","Darmstadtium","Roentgenium","Copernicium","Nihonium","Flerovium","Moscovium","Livermorium","Tennessine","Oganesson"]
    b = [1.0080,4.00260,7,9.012183,10.81,12.011,14.007,15.999,18.99840316,20.180,22.9897693,24.305, 26.981538,28.085,30.97376200,32.07,35.45,39.9,39.0983,40.08,  44.95591,47.867, 50.9415,51.996, 54.93804,55.84,58.93319,58.693,63.55,65.4,69.723, 72.63,74.92159,78.97,79.90,83.80,85.468,87.62,88.90584,91.22,  92.90637,95.95,96.90636,101.1,102.9055,106.42,107.868,112.41,114.818,118.71,121.760,127.6,126.9045,131.29,132.9054520,137.33, 138.9055,140.116,140.90766,144.24,144.91276,150.4,151.964,157.2,158.92535,162.500,164.93033,167.26,168.93422,173.05, 174.9668,178.49, 180.9479,183.84, 186.207,190.2,192.22, 195.08,196.96657,200.59, 204.383,207,208.98040,208.98243,209.98715,222.01758,223.01973,226.02541,227.02775,232.038,231.03588,238.0289,237.048172,244.06420,243.061380,247.07035,247.07031,251.07959,252.0830,257.09511,258.09843,259.10100,266.120,267.122,268.126,269.128,270.133,269.1336,277.154,282.166,282.169,286.179,286.182,290.192,290.196,293.205,294.211,295.216]
    c = ["1s1","1s2","[He]2s1","[He]2s2","[He]2s22p1","[He]2s22p2","[He]2s22p3","[He]2s22p4","[He]2s22p5","[He]2s22p6","[Ne]3s1","[Ne]3s2","[Ne]3s23p1","[Ne]3s23p2","[Ne]3s23p3","[Ne]3s23p4","[Ne]3s23p5","[Ne]3s23p6","[Ar]4s1","[Ar]4s2","[Ar]3d14s2","[Ar]3d24s2","[Ar]3d34s2","[Ar]3d54s1","[Ar]3d54s2","[Ar]3d64s2","[Ar]3d74s2","[Ar]3d84s2","[Ar]3d104s1","[Ar]3d104s2","[Ar]3d104s24p1","[Ar]3d104s24p2","[Ar]3d104s24p3","[Ar]3d104s24p4","[Ar]3d104s24p5","[Ar]3d104s24p6","[Kr]5s1","[Kr]5s2","[Kr]4d15s2","[Kr]4d25s2","[Kr]4d45s1","[Kr]4d55s1","[Kr]4d55s2","[Kr]4d75s1","[Kr]4d85s1","[Kr]4d10","[Kr]4d105s1","[Kr]4d105s2","[Kr]4d105s25p1","[Kr]4d105s25p2","[Kr]4d105s25p3","[Kr]4d105s25p4","[Kr]4d105s25p5","[Kr]4d105s25p6","[Xe]6s1","[Xe]6s2","[Xe]5d16s2","[Xe]4f15d16s2","[Xe]4f36s2","[Xe]4f46s2","[Xe]4f56s2","[Xe]4f66s2","[Xe]4f76s2","[Xe]4f75d16s2","[Xe]4f96s2","[Xe]4f106s2","[Xe]4f116s2","[Xe]4f126s2","[Xe]4f136s2","[Xe]4f146s2","[Xe]4f145d16s2","[Xe]4f145d26s2","[Xe]4f145d36s2","[Xe]4f145d46s2","[Xe]4f145d56s2","[Xe]4f145d66s2","[Xe]4f145d76s2","[Xe]4f145d96s1","[Xe]4f145d106s1","[Xe]4f145d106s2","[Xe]4f145d106s26p1","[Xe]4f145d106s26p2","[Xe]4f145d106s26p3","[Xe]4f145d106s26p4","[Xe]4f145d106s26p5","[Xe]4f145d106s26p6","[Rn]7s1","[Rn]7s2","[Rn]6d17s2","[Rn]6d27s2","[Rn]5f26d17s2","[Rn]5f36d17s2","[Rn]5f46d17s2","[Rn]5f67s2","[Rn]5f77s2","[Rn]5f76d17s2","[Rn]5f97s2","[Rn]5f107s2","[Rn]5f117s2","[Rn]5f127s2","[Rn]5f137s2","[Rn]5f147s2","[Rn]5f147s27p1","[Rn]5f146d27s2","[Rn]5f146d37s2","[Rn]5f146d47s2","[Rn]5f146d57s2","[Rn]5f146d67s2","[Rn]5f146d77s2","[Rn]5f146d97s1","[Rn]5f146d107s1","[Rn]5f146d107s2","[Rn]5f146d107s27p1","[Rn]5f146d107s27p2","[Rn]5f146d107s27p3","[Rn]5f146d107s27p4","[Rn]5f146d107s27p5","[Rn]5f146d107s27p6"]
    d = [2.20,"no data",0.98,1.57,2.04,2.55,3.04,3.44,3.98,"no data",0.93,1.31,1.61,1.90,2.19,2.58,3.16,"no data",0.82,1.00,1.36,1.54,1.63,1.66,1.55,1.83,1.88,1.91,1.90,1.65,1.81,2.01,2.18,2.55,2.96,3.00,0.82,0.95,1.22,1.33,1.6,2.16,1.9,2.2,2.28,2.20,1.93,1.69,1.78,1.96,2.05,2.1,2.66,2.6,0.79,0.89,1.10,1.12,1.13,1.14,1.13,1.17,1.2,1.2,1.22,1.23,1.24,1.24,1.25,1.1,1.27,1.3,1.5,2.36,1.9,2.2,2.2,2.28,2.54,2.00,1.62,2.33,2.02,2.0,2.2,"no data",0.7,0.89,1.1,1.3,1.5,1.38,1.36,1.28,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,"no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data","no data"]
    def my_callback(self, widget,element, element_picture):
        name = self.a[element]
        mass = self.b[element]
        elec = self.c[element]
        electron = self.d[element]
        number = element+1
        my_image = toga.Image(self.paths.app / element_picture)
        self.real = toga.ImageView(my_image)
        self.info = 'Element name: {}\nAtomic Number: {}\nAtomic Mass: {}\nElectron Configuration: {}\nElectronegativity: {}'.format(name, number,mass,elec, electron)

        image_window = toga.Window()
        image_view = toga.ImageView(my_image, style=Pack(width=200, height=200))
        info_label = toga.Label(self.info, style=Pack(padding=10))
        image_window.content = toga.Box(children=[image_view, info_label], style=Pack(direction=ROW))
        image_window.show()
    
        
def main():
    return Perodictable()

